//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q06CallAStoredProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Old_Date { get; set; }
        public Nullable<System.DateTime> New_Date { get; set; }
        public string Old_Task { get; set; }
        public string New_Task { get; set; }
        public Nullable<int> Old_Hours { get; set; }
        public Nullable<int> New_Hours { get; set; }
        public string Old_Comments { get; set; }
        public string New_Comments { get; set; }
        public string Command_type { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
